Get started guide for RIF Relay Sample dApp SDK
rsksmart/rif-relay pull request #257
Opened 2023-12-12 14:21 UTC by zdaodu-iov

## What

- The guide includes the process to get started with the RIF Relay Sample dApp SDK.

## Why

- The purpose of these changes is to facilitate developers and users in effectively utilizing the RIF Relay
- The guide aims to lower the entry barrier for new users and enhance the understanding of the SDK’s capabilities.

## Refs

- (optional: include links to other issues, PRs, tickets, etc)

2023-12-13 13:21 UTC, antomor reviewed
@zdaodu-iov Thank you for the proposal, but I think that it's not a good idea to include the steps required to run an RSKj node into the relay guide. IMHO This is something that should go in a common place, likely in the developer portal and eventually, include here as a link. Adding this guide here may mean that we need to maintain it in future, and I'd avoid it

2023-12-13 14:18 UTC, zdaodu-iov commented
@antomor I agree. Actually this PR is still a work in progress. I have a [PR](https://github.com/rsksmart/devportal/pull/944) open in the dev portal to add these instructions and then I'll link to it from here.

2023-12-13 14:45 UTC, antomor commented
> @antomor I agree. Actually this PR is still a work in progress. I have a [PR](https://github.com/rsksmart/devportal/pull/944) open in the dev portal to add these instructions and then I'll link to it from here.

Great, thank you! I'll review it again once it's ready 👍🏼

2023-12-15 09:37 UTC, zdaodu-iov commented
@antomor the PR is now ready for review, thanks!

2023-12-18 08:38 UTC, antomor commented on Readme.md
> +The setup of RIF Relay contracts and server is a multi-step process. It involves deploying on-chain components, meeting installation requirements, and using various development tools. For detailed in
```suggestion
The setup of RIF Relay Contracts and Server is a multi-step process. It involves deploying on-chain components, meeting installation requirements, and using various development tools. For detailed instructions and necessary resources for this setup, see [Setup RIF Relay Contract and Server guide](https://dev.rootstock.io/guides/rif-relay/deployment/). 
```

2023-12-18 08:42 UTC, antomor commented on Readme.md
> +This is a sample dApp to show you how to submit relayed transactions to the Rootstock blockchain using the [RIF Relay SDK](https://github.com/infuy/relaying-services-sdk). Connect to the dApp with Me
```suggestion
This is a sample dApp to show you how to submit relayed transactions to the Rootstock blockchain using the [RIF Relay Client](https://github.com/rsksmart/rif-relay-client). Connect to the dApp with MetaMask for signing transactions with the account that owns the Smart Wallets. For more detials, see [RIF Relay Sample dApp](https://github.com/rsksmart/rif-relay-sample-dapp).
```

2023-12-18 08:43 UTC, antomor requested changes
@zdaodu-iov thank you for the changes, I've left some minor improvements.

2023-12-18 09:55 UTC, antomor approved these changes

2023-12-21 09:13 UTC, owans approved these changes

2023-12-21 09:13 UTC, owans commented on Readme.md
> +We've created a sample dApp to showcase how users can submit relayed transactions to the RSK blockchain using the RIF Relay Sample dApp SDK. For details, see [RIF Relaying Services SDK sample dApp](h
```suggestion
We've created a sample dApp to showcase how users can submit relayed transactions to the Rootstock blockchain using the RIF Relay Sample dApp SDK. For details, see [RIF Relaying Services SDK sample dApp](https://github.com/rsksmart/rif-relay-sample-dapp).
```

2023-12-22 11:36 UTC, antomor reviewed
@zdaodu-iov @owans Not sure if this was intended, but almost all of the previous changes got reverted

2024-01-08 10:57 UTC, antomor approved these changes

2024-01-08 10:57 UTC, merged